import type { EvidenceGrade } from "@/components/digital-twin/types";

/**
 * Evidence grade, per technical mission §5. The product's core promise is that
 * a verified fact, an unreviewed AI extraction, a deterministic rule result and
 * a scenario projection never look alike — so this chip is the structural
 * device that runs through the whole interface.
 */
const GRADES: Record<EvidenceGrade, { label: string; description: string; classes: string }> = {
  verified: {
    label: "Verified",
    description: "Entered or extracted from a source document and approved by a doctor",
    classes: "border-state-green/40 bg-state-green/10 text-state-green",
  },
  ai_unverified: {
    label: "AI · unverified",
    description: "Detected by the model, awaiting doctor confirmation",
    classes: "border-ai/40 bg-ai/10 text-ai",
  },
  clinical_rule: {
    label: "Clinical rule",
    description: "Deterministic check from the versioned rule catalog",
    classes: "border-signal/40 bg-signal/10 text-signal",
  },
  ai_interpretation: {
    label: "AI interpretation",
    description: "Probabilistic explanation generated by the model",
    classes: "border-ai/40 bg-ai/10 text-ai",
  },
  projection: {
    label: "Scenario projection",
    description: "Illustrative model-based estimate, not a medical guarantee",
    classes: "border-electric/40 bg-electric/10 text-electric",
  },
};

export function ProvenanceChip({ grade }: { grade: EvidenceGrade }) {
  const config = GRADES[grade];
  return (
    <span
      title={config.description}
      className={`inline-flex items-center gap-1.5 rounded border px-2 py-0.5 font-mono text-[10px] uppercase tracking-[0.12em] ${config.classes}`}
    >
      <span aria-hidden className="h-1 w-1 rounded-full bg-current" />
      {config.label}
    </span>
  );
}

export const EVIDENCE_GRADES = GRADES;
